#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="${RK_YOLO_LIVE_BIN:-${ROOT}/build/rk_yolo_live_rtsp}"

SOURCE="${1:-${RK_YOLO_SOURCE:-/dev/video48}}"
MODEL="${RK_YOLO_MODEL:-/home/ubuntu/eclipse-workspace/eclipse-workspace/training_runs/drone_hard_v1_ft_640_20e/weights/best.end2end_false.op12.rk3588.fp.v232.hard_v1.rknn}"
MOUNT="${RK_YOLO_MOUNT:-/drone}"
WIDTH="${RK_YOLO_WIDTH:-640}"
HEIGHT="${RK_YOLO_HEIGHT:-480}"
FPS="${RK_YOLO_FPS:-15}"
SCORE="${RK_YOLO_SCORE:-0.20}"
NMS="${RK_YOLO_NMS:-0.45}"
PORT="${RK_YOLO_RTSP_PORT:-8554}"
DETECT_EVERY_N="${RK_YOLO_DETECT_EVERY_N:-3}"

# Default defense against bounding-box jumping in live demonstrations.
export RK_YOLO_DYNAMIC_ROI="${RK_YOLO_DYNAMIC_ROI:-0}"
export RK_YOLO_BOX_SMOOTH="${RK_YOLO_BOX_SMOOTH:-1}"
export RK_YOLO_BOX_SMOOTH_ALPHA="${RK_YOLO_BOX_SMOOTH_ALPHA:-0.55}"
export RK_YOLO_BOX_SMOOTH_IOU="${RK_YOLO_BOX_SMOOTH_IOU:-0.05}"
export RK_YOLO_TARGET_LOCK="${RK_YOLO_TARGET_LOCK:-1}"
export RK_YOLO_LOCK_HOLD_FRAMES="${RK_YOLO_LOCK_HOLD_FRAMES:-8}"
export RK_YOLO_LOCK_MIN_SCORE="${RK_YOLO_LOCK_MIN_SCORE:-0.20}"
export RK_YOLO_LOCK_MIN_IOU="${RK_YOLO_LOCK_MIN_IOU:-0.02}"
export RK_YOLO_LOCK_MAX_CENTER_STEP="${RK_YOLO_LOCK_MAX_CENTER_STEP:-0.28}"
export RK_YOLO_LOCK_MAX_SIZE_STEP="${RK_YOLO_LOCK_MAX_SIZE_STEP:-0.45}"
export RK_YOLO_LOCK_ALPHA="${RK_YOLO_LOCK_ALPHA:-0.65}"

# Mature camera behavior: short AF after zoom, then lock focus to avoid hunting.
export RK_YOLO_CAMERA_TUNE="${RK_YOLO_CAMERA_TUNE:-1}"
export RK_YOLO_CAMERA_MATCH="${RK_YOLO_CAMERA_MATCH:-HBS Camera}"
export RK_YOLO_CAMERA_ZOOM="${RK_YOLO_CAMERA_ZOOM:-20}"
export RK_YOLO_CAMERA_FOCUS_AUTO="${RK_YOLO_CAMERA_FOCUS_AUTO:-1}"
export RK_YOLO_CAMERA_FOCUS="${RK_YOLO_CAMERA_FOCUS:-260}"
export RK_YOLO_CAMERA_SETTLE_MS="${RK_YOLO_CAMERA_SETTLE_MS:-350}"
export RK_YOLO_CAMERA_WARMUP_GRABS="${RK_YOLO_CAMERA_WARMUP_GRABS:-6}"
export RK_YOLO_CAMERA_FOCUS_STARTUP_LOCK="${RK_YOLO_CAMERA_FOCUS_STARTUP_LOCK:-1}"
export RK_YOLO_CAMERA_FOCUS_LOCK_MS="${RK_YOLO_CAMERA_FOCUS_LOCK_MS:-1200}"
export RK_YOLO_CAMERA_REFOCUS_AFTER_ZOOM="${RK_YOLO_CAMERA_REFOCUS_AFTER_ZOOM:-1}"
export RK_YOLO_CAMERA_REFOCUS_ZOOM_DELTA="${RK_YOLO_CAMERA_REFOCUS_ZOOM_DELTA:-8}"
export RK_YOLO_CAMERA_REFOCUS_COOLDOWN="${RK_YOLO_CAMERA_REFOCUS_COOLDOWN:-60}"
export RK_YOLO_CAMERA_REFOCUS_SETTLE_MS="${RK_YOLO_CAMERA_REFOCUS_SETTLE_MS:-1000}"
export RK_YOLO_CAMERA_REFOCUS_FALLBACK_FRAMES="${RK_YOLO_CAMERA_REFOCUS_FALLBACK_FRAMES:-210}"

# Auto zoom is intentionally moderate; change these env vars for more aggressive demos.
export RK_YOLO_AUTO_ZOOM="${RK_YOLO_AUTO_ZOOM:-1}"
export RK_YOLO_AUTO_ZOOM_MIN="${RK_YOLO_AUTO_ZOOM_MIN:-0}"
export RK_YOLO_AUTO_ZOOM_MAX="${RK_YOLO_AUTO_ZOOM_MAX:-60}"
export RK_YOLO_AUTO_ZOOM_STEP="${RK_YOLO_AUTO_ZOOM_STEP:-4}"
export RK_YOLO_AUTO_ZOOM_COOLDOWN="${RK_YOLO_AUTO_ZOOM_COOLDOWN:-12}"
export RK_YOLO_AUTO_ZOOM_LOST_FRAMES="${RK_YOLO_AUTO_ZOOM_LOST_FRAMES:-45}"
export RK_YOLO_AUTO_ZOOM_MIN_RATIO="${RK_YOLO_AUTO_ZOOM_MIN_RATIO:-0.055}"
export RK_YOLO_AUTO_ZOOM_MAX_RATIO="${RK_YOLO_AUTO_ZOOM_MAX_RATIO:-0.24}"

echo "Starting default live demo:"
echo "  source=${SOURCE}"
echo "  model=${MODEL}"
echo "  rtsp=rtsp://<board-ip>:${PORT}${MOUNT}"
echo "  score=${SCORE}, detect_every_n=${DETECT_EVERY_N}, target_lock=${RK_YOLO_TARGET_LOCK}, auto_zoom=${RK_YOLO_AUTO_ZOOM}"

exec "${BIN}" "${SOURCE}" "${MODEL}" "${MOUNT}" "${WIDTH}" "${HEIGHT}" "${FPS}" \
  "${SCORE}" "${NMS}" "${PORT}" "${DETECT_EVERY_N}"
